### ISSUE TITLE
Template Repo

### ISSUE THREAD

**Issue by smolck** [0x0f0f0f/dune-starter-project#1]
It might be advantageous to change this repository into a template repo so others can create new projects with the same structure and files. 

If you're unfamiliar with template repositories, see https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

See also [these instructions for creating a repo from a template](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template) for an example of how this would/could be used.

**Comment by 0x0f0f0f** [comment]
Thank you! :)
